fix defragmentation OpsDefinition

diff --git a/addons/etcd/opsdefinitions/defragmentation.yaml b/addons/etcd/opsdefinitions/defragmentation.yaml
--- a/addons/etcd/opsdefinitions/defragmentation.yaml
+++ b/addons/etcd/opsdefinitions/defragmentation.yaml
@@ -7,6 +7,28 @@ spec:
     - rule:
         expression: '{{ eq .component.status.phase "Running" }}'
         message: "Component is not in Running status."
+  podInfoExtractors:
+    - name: etcdInfo
+      podSelector:
+        multiPodSelectionPolicy: Any
+      env:
+        - name: PEERS
+          valueFrom:
+            envRef:
+              envName: PEERS
+        - name: TMP_CONFIG_PATH
+          valueFrom:
+            envRef:
+              envName: TMP_CONFIG_PATH
+        - name: TLS_MOUNT_PATH
+          valueFrom:
+            envRef:
+              envName: TLS_MOUNT_PATH
+      volumeMounts:
+        - name: tls
+          mountPath: /etc/pki/tls
+        - name: data
+          mountPath: /var/run/etcd
   componentInfos:
   - componentDefinitionName: etcd-v3.5.15
   actions:
@@ -15,15 +37,49 @@ spec:
       workload:
         type: Job
         backoffLimit: 2
+        podInfoExtractorName: etcdInfo
         podSpec:
           containers:
             - name: etcd-defragmentation
               image: quay.io/coreos/etcd:v3.5.6
               imagePullPolicy: IfNotPresent
               command:
-                - bash
+                - sh
                 - -c
                 - |
-                  set -e
-                  ENDPOINT=http://${KB_CLUSTER_COMP_NAME}-0.${KB_COMP_HEADLESS_SVC_NAME}.${KB_OPS_NAMESPACE}.svc${CLUSTER_DOMAIN}:2379
-                  etcdctl defrag --endpoints=$ENDPOINT
+                  getClientProtocol() {
+                    # check client tls if is enabled
+                    line=$(grep 'advertise-client-urls' ${TMP_CONFIG_PATH})
+                    if echo $line | grep -q 'https'; then
+                      echo "https"
+                    elif echo $line | grep -q 'http'; then
+                      echo "http"
+                    fi
+                  }
+                  
+                  execEtcdctl() { 
+                    local endpoints=$1
+                    shift
+                    clientProtocol=$(getClientProtocol)
+                    tlsDir=$TLS_MOUNT_PATH
+                    # check if the clientProtocol is https and the tlsDir is not empty
+                    if [ $clientProtocol = "https" ] && [ -d "$tlsDir" ] && [ -s "${tlsDir}/ca.crt" ] && [ -s "${tlsDir}/tls.crt" ] && [ -s "${tlsDir}/tls.key" ]; then
+                      etcdctl --endpoints=${endpoints} --cacert=${tlsDir}/ca.crt --cert=${tlsDir}/tls.crt --key=${tlsDir}/tls.key "$@"
+                    elif [ $clientProtocol = "http" ]; then
+                      etcdctl --endpoints=${endpoints} "$@"
+                    else
+                      echo "ERROR: bad etcdctl args: clientProtocol:${clientProtocol}, endpoints:${endpoints}, tlsDir:${tlsDir}, please check!"
+                      exit 1
+                    fi
+                    # check if the etcdctl command was successful
+                    if [ $? -ne 0 ]; then
+                      echo "etcdctl command failed"
+                      exit 1
+                    fi
+                  }
+
+                  for PEER in $(echo $PEERS | tr ',' ' '); do
+                    ENDPOINTS="${ENDPOINTS}${PEER}:2379,"
+                  done
+                  ENDPOINTS=$(echo ${ENDPOINTS} | sed 's/,$//')
+                  execEtcdctl "${ENDPOINTS}" defrag
