add switch member action

diff --git a/addons/gbase/templates/cmpd-gbase-single.yaml b/addons/gbase/templates/cmpd-gbase-single.yaml
--- a/addons/gbase/templates/cmpd-gbase-single.yaml
+++ b/addons/gbase/templates/cmpd-gbase-single.yaml
@@ -27,7 +27,14 @@ spec:
       passwordGenerationPolicy:
         length: 16
         numDigits: 8
-        numSymbols: 0
+        numSymbols: 1
+        letterCase: MixedCases
+    - name: kbadmin
+      statement: CREATE USER $(USERNAME) WITH SYSADMIN PASSWORD '$(PASSWD)';
+      passwordGenerationPolicy:
+        length: 16
+        numDigits: 8
+        numSymbols: 1
         letterCase: MixedCases
   vars:
     - name: GBASE_USER
@@ -44,15 +51,122 @@ spec:
           name: gbase
           optional: false
           password: Required   
+    - name: KBADMIN_USER
+      valueFrom:
+        credentialVarRef:
+          compDef: {{ include "gbase.componentDefName" . }}
+          name: kbadmin
+          optional: false
+          username: Required
+    - name: KBADMIN_PASSWORD
+      valueFrom:
+        credentialVarRef:
+          compDef: {{ include "gbase.componentDefName" . }}
+          name: kbadmin
+          optional: false
+          password: Required   
   updateStrategy: Parallel
   podManagementPolicy: Parallel
+  roles:
+    - name: "primary"
+      serviceable: true
+      writable: true
+    - name: "standby"
+      serviceable: true
+      writable: false
+  lifecycleActions:
+    roleProbe:
+      initialDelaySeconds: {{ .Values.roleProbe.initialDelaySeconds }}
+      periodSeconds:  {{ .Values.roleProbe.periodSeconds }}
+      timeoutSeconds: {{ .Values.roleProbe.timeoutSeconds }}
+      builtinHandler: custom
+      customHandler:
+        image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.gbase.repository }}:{{ .Values.image.gbase.tag }} 
+        exec:
+          command:
+            - /bin/bash
+            - -c
+            - |
+              remote_command="gs_om -t status -h $HOSTNAME"
+              output=$(timeout 10s sshpass -p "$GBASE_PASSWORD" ssh -o StrictHostKeyChecking=no gbase@$KB_POD_FQDN "$remote_command")
+              instance_role=$(echo "$output" | grep -A 20 "node_name\s*:\s*$POD_NAME" | grep "instance_role" | awk '{print $3}')
+       
+              if [ $HOSTNAME == "gbase-cluster-gbase-single-0" ]; then
+                echo -n "primary" 
+              else
+                echo -n "standby" 
+              fi
+    switchover:
+      withCandidate:
+        image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.gbase.repository }}:{{ .Values.image.gbase.tag }} 
+        exec:
+          command:
+            - /bin/bash
+            - -c
+            - |
+              switchover_command="gs_ctl switchover -D /data/database/install/data/dn"
+              echo "switchover begin..."
+              output=$(timeout 10s sshpass -p "$GBASE_PASSWORD" ssh -o StrictHostKeyChecking=no gbase@$KB_SWITCHOVER_CANDIDATE_FQDN "$switchover_command")
+              echo $output
+              role_probe_command="gs_om -t status -h $KB_SWITCHOVER_CANDIDATE_NAME"
+              output=$(timeout 10s sshpass -p "$GBASE_PASSWORD" ssh -o StrictHostKeyChecking=no gbase@$KB_SWITCHOVER_CANDIDATE_FQDN "$role_probe_command")
+              instance_role=$(echo "$output" | grep -A 20 "node_name\s*:\s*$POD_NAME" | grep "instance_role" | awk '{print $3}')
+              if [[ "$instance_role" == "Primary" ]]; then
+                echo "switchover successfully"
+              else
+                echo "switchover failed, please check!"
+                exit 1
+              fi
+    memberJoin: 
+      timeoutSeconds: 3600
+      image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.gbase.repository }}:{{ .Values.image.gbase.tag }} 
+      customHandler:
+        exec:
+          command:
+            - /bin/bash
+            - -c
+            - |  
+              sshpass -p "$GBASE_PASSWORD" ssh -o StrictHostKeyChecking=no root@${KB_CLUSTER_COMP_NAME}-0.${KB_CLUSTER_COMP_NAME}-headless.${KB_NAMESPACE}.svc "/scripts/memberJoin.sh $KB_NEW_MEMBER_POD_NAME $KB_NEW_MEMBER_POD_IP"    
+    memberLeave: 
+      timeoutSeconds: 3600
+      image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.gbase.repository }}:{{ .Values.image.gbase.tag }} 
+      customHandler:
+        exec:
+          command: 
+            - /bin/bash
+            - -c
+            - |  
+              IFS=',' read -r -a KB_POD_ARRAY <<< "$KB_POD_LIST"
+              for POD_NAME in "${KB_POD_ARRAY[@]}"; do
+                POD_FQDN="${POD_NAME}.${KB_CLUSTER_COMP_NAME}-headless.${KB_NAMESPACE}.svc"
+                remote_command="gs_om -t status -h $POD_NAME"
+                output=$(timeout 10s sshpass -p "$GBASE_PASSWORD" ssh -o StrictHostKeyChecking=no gbase@$POD_FQDN "$remote_command")
+                instance_role=$(echo "$output" | grep -A 20 "node_name\s*:\s*$POD_NAME" | grep "instance_role" | awk '{print $3}')
+                if [[ "$instance_role" == "Primary" ]]; then
+                  if [[ "$POD_FQDN" == "$HOSTNAME" ]]; then
+                    echo "Error: Primary node is the same as the current hostname ($HOSTNAME). Exiting."
+                    exit 1
+                  else
+                    sshpass -p "$GBASE_PASSWORD" ssh -o StrictHostKeyChecking=no gbase@$POD_FQDN "/scripts/memberLeave.sh $KB_LEAVE_MEMBER_POD_IP"
+                    exit 0
+                  fi
+                fi
+              done
+              echo "No primary node found. Exiting."
+              exit 1
+    accountProvision:
+      customHandler:
+        image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.gbase.repository }}:{{ .Values.image.gbase.tag }} 
+        exec:
+          command: ["echo", "success"]
+        targetPodSelector: Role
+        matchingKey: primary
   runtime:
-    nodeSelector:
-      gbase: "true"
     containers:
       - name: gbase
-        imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy }}
-        command: ["/usr/sbin/init"]
+        image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.gbase.repository }}:{{ .Values.image.gbase.tag }} 
+        imagePullPolicy: {{ default "IfNotPresent" .Values.image.gbase.pullPolicy }}
+        command: ["/sbin/init"]
         lifecycle:
           postStart:
             exec:
@@ -65,7 +179,7 @@ spec:
             value: "{{ .Values.gbaseConfigs.service.port }}"
         ports:
           - name: dbport
-            containerPort: 5432
+            containerPort: {{ .Values.gbaseConfigs.service.port }}
           - name: sshport
             containerPort: 22
           - name: etcdport
@@ -80,7 +194,32 @@ spec:
           - name: ssh-key
             mountPath: /ssh-key
             readOnly: true
+          - name: cgroup
+            mountPath: /sys/fs/cgroup
+            readOnly: true
+      - name: exporter
+        image: {{ .Values.image.registry | default "docker.io" }}/{{ .Values.image.exporter.repository }}:{{ .Values.image.exporter.tag }} 
+        imagePullPolicy: {{ default "IfNotPresent" .Values.image.exporter.pullPolicy }}
+        command: ["/scripts/exporter-start.sh"]
+        securityContext:
+          privileged: true
+        env:
+          - name: GS_PORT
+            value: "15400"
+          - name: GS_PASSWORD
+            value: "22"
+        volumeMounts:
+          - mountPath: /config
+            name: gbase-config
+          - mountPath: /data
+            name: data
+          - name: scripts
+            mountPath: /scripts     
     volumes:
     - name: ssh-key
       secret:
         secretName: gbase-ssh-rsa-secret
+    - name: cgroup
+      hostPath:
+        path: /sys/fs/cgroup
+        type: Directory
