chore: support new switchover action (#1338)

diff --git a/addons/mongodb/templates/cmpd.yaml b/addons/mongodb/templates/cmpd.yaml
--- a/addons/mongodb/templates/cmpd.yaml
+++ b/addons/mongodb/templates/cmpd.yaml
@@ -92,7 +92,16 @@ spec:
           - /bin/sh
           - -c
           - |
-            /tools/syncerctl switchover --primary "$KB_LEADER_POD_NAME" ${KB_SWITCHOVER_CANDIDATE_NAME:+--candidate "$KB_SWITCHOVER_CANDIDATE_NAME"}
+            if [ -z "$KB_SWITCHOVER_ROLE" ]; then
+                echo "role can't be empty"
+                exit 1
+            fi
+
+            if [ "$KB_SWITCHOVER_ROLE" != "primary" ]; then
+                exit 0
+            fi
+
+            /tools/syncerctl switchover --primary "$KB_SWITCHOVER_CURRENT_NAME" ${KB_SWITCHOVER_CANDIDATE_NAME:+--candidate "$KB_SWITCHOVER_CANDIDATE_NAME"}
   runtime:
     initContainers:
       - command:
