fix

diff --git a/addons/minio/templates/cpmd.yaml b/addons/minio/templates/cpmd.yaml
--- a/addons/minio/templates/cpmd.yaml
+++ b/addons/minio/templates/cpmd.yaml
@@ -1,12 +1,4 @@
-{{ $drivesPerNode := .Values.drivesPerNode | int }}
 {{ $scheme := .Values.tls.enabled | ternary "https" "http" }}
-{{ $mountPath := .Values.mountPath }}
-{{ $bucketRoot := or ($.Values.bucketRoot) ($.Values.mountPath) }}
-{{ $subPath := .Values.persistence.subPath }}
-{{ $penabled := .Values.persistence.enabled }}
-{{ $accessMode := .Values.persistence.accessMode }}
-{{ $storageClass := .Values.persistence.storageClass }}
-{{ $psize := .Values.persistence.size }}
 
 apiVersion: apps.kubeblocks.io/v1alpha1
 kind: ComponentDefinition
@@ -16,7 +8,7 @@ metadata:
     {{- include "minio.labels" . | nindent 4 }}
 spec:
   provider: kubeblocks
-  description: Minio
+  description: Minio is a High Performance Object Storage.
   serviceKind: minio
   serviceVersion: {{ .Chart.Version }}
 
@@ -42,6 +34,28 @@ spec:
           name: root
           optional: false
           password: Required
+
+  lifecycleActions:
+    roleProbe:
+      builtinHandler: custom
+      customHandler:
+        exec:
+          command:
+            - /bin/bash
+            - -c
+            - |
+              mc config host add minio http://127.0.0.1:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
+
+  services:
+  - name: default
+    spec:
+      ports:
+        - name: api
+          port: 9000
+          targetPort: api
+        - name: console
+          port: 9001
+          targetPort: console
 
   configs:
     - name: minio-configuration
@@ -91,6 +105,25 @@ spec:
               echo "minio config don't existed"
               exit
             fi
+
+            # init bucket if set 
+            buckets=$MINIO_BUCKETS
+            if [ -n "$buckets" ]; then
+                IFS=',' read -ra BUCKET_ARRAY <<< "$buckets"
+                for bucket in "${BUCKET_ARRAY[@]}"; do
+                    bucket=$(echo $bucket)
+
+                    directory="/data/$bucket"
+                    mkdir -p "$directory"
+
+                    if [ $? -eq 0 ]; then
+                        echo "Successfully init bucket: $directory"
+                    else
+                        echo "Failed to init bucket: $directory"
+                    fi
+                done
+            fi
+
             # read the content
             content=$(cat "$FILE")
             content=$(echo "$content" | tr -d '[]')
@@ -99,11 +132,11 @@ spec:
             for ((i=0; i < ${#replicas[@]}; i++)); do
                 if [ $i -eq 0 ]; then
                     cur=${replicas[i]}
-                    server+="{{ $scheme }}://$KB_CLUSTER_COMP_NAME-{0...$((cur-1))}.$KB_CLUSTER_COMP_NAME-headless.$KB_NAMESPACE.svc.{{ $.Values.clusterDomain }}{{ $bucketRoot }}"
+                    server+="{{ $scheme }}://$KB_CLUSTER_COMP_NAME-{0...$((cur-1))}.$KB_CLUSTER_COMP_NAME-headless.$KB_NAMESPACE.svc.{{ $.Values.clusterDomain }}/data"
                 else
                     prev=${replicas[i-1]}
                     cur=${replicas[i]}
-                    server+=" {{ $scheme }}://$KB_CLUSTER_COMP_NAME-{$((prev))...$((cur-1))}.$KB_CLUSTER_COMP_NAME-headless.$KB_NAMESPACE.svc.{{ $.Values.clusterDomain }}{{ $bucketRoot }}"
+                    server+=" {{ $scheme }}://$KB_CLUSTER_COMP_NAME-{$((prev))...$((cur-1))}.$KB_CLUSTER_COMP_NAME-headless.$KB_NAMESPACE.svc.{{ $.Values.clusterDomain }}/data"
                 fi
             done
             echo "the minio server pool is $server"
@@ -116,22 +149,6 @@ spec:
           - name: console
             protocol: TCP
             containerPort: {{ .Values.minioConsolePort }}
-        readinessProbe:
-          tcpSocket:
-            port: api
-          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
-          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
-          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
-          successThreshold: {{ .Values.readinessProbe.successThreshold }}
-          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
-        startupProbe:
-          tcpSocket:
-            port: api
-          initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
-          periodSeconds: {{ .Values.startupProbe.periodSeconds }}
-          timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
-          successThreshold: {{ .Values.startupProbe.successThreshold }}
-          failureThreshold: {{ .Values.startupProbe.failureThreshold }} 
         env:
           - name: MINIO_ROOT_USER
             value: $(MINIO_ROOT_USER)
@@ -141,9 +158,9 @@ spec:
             value: "off"
         volumeMounts:
           - name: data
-            mountPath: {{ $mountPath }}
+            mountPath: /data
           - name: minio-config
             mountPath: /minio-config
   volumes:
-  - name: export
+  - name: data
     needSnapshot: true
